version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-deps
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
